countries: ["Cote D'Ivoire", "Ghana", "Kenya", 'Madagascar', "Senegal", "Nigeria", "Philippines"]
survey_ids: ["CI2021DHS", "GH2022DHS", "KE2022DHS", "MD2021DHS", "SN2019DHS", "NG2018DHS", "PH2022DHS"]
completeness_threshold: 0.3
n_holdouts: 5
n_imputations: 5
fields:
  ids: ['cluster', 'bh_year', 'hh_id', 'w_id', 'birth_id', 'admin1_code', 'admin1_name']
  outcome: 'died'
  hidden: [
    'age_group', 'c_birth_year', 'c_alive', 'c_age_months', 'c_died_pnn', 'b_10y_prior',
    'w_sample_weight', 'int_month_cmc', 'c_died_age_months', 'c_birth_int', "w_born_cmc"
  ]
  spatial_covariates: [
    'Drought_Episodes', 'Elevation', 'Global_Human_Footprint', 'Land_Surface_Temperature',
    'Livestock_Cattle', 'Malaria_Incidence', 'Nightlights_Composite', 'Precipitation'
  ]
age_groups:
  a01mo: [1, 6]
  a06mo: [6, 12]
  a12mo: [12, 24]
  a24mo: [24, 36]
  a36mo: [36, 48]
  a48mo: [48, 60]
versions:
  prepared_data: '20240516'
  imputed_data: '20240516'
  model_results: '20240516'
directories:
  r_package:
    versioned: FALSE
    path: '~/repos/usaid-mch-ml/r-package'
  metadata:
    versioned: FALSE
    path: '~/temp_data/usaid-mch-ml/metadata'
    files:
      codebook: 'codebook_20240516.csv'
  prepared_data:
    versioned: TRUE
    path: '~/temp_data/usaid-mch-ml/prepared_data'
  model_results:
    versioned: TRUE
    path: '~/temp_data/usaid-mch-ml/model_results'
  imputed_data:
    versioned: TRUE
    path: '~/temp_data/usaid-mch-ml/imputed_data'
  shps:
    versioned: FALSE
    path: '/mnt/c/Users/Lenovo/OneDrive - Henry Spatial Analysis LLC/Henry Spatial Analysis/DHS/Sharing/Updated GAUL shapefile/updated_gaul_v2'
    files:
      adm0: 'g2015_2014_0.shp'
      adm1: 'g2015_2014_1.shp'
      adm2: 'g2015_2014_2.shp'
