countries: ["Cote D'Ivoire", "Ghana", "Kenya", 'Madagascar', "Senegal", "Nigeria", "Philippines"]
survey_ids: ["CI2021DHS", "GH2022DHS", "KE2022DHS", "MD2021DHS", "SN2019DHS", "NG2018DHS", "PH2022DHS"]
map_indicators: ['stunting', 'wasting', 'hhwi_cont', 'first_birth_u18', 'w_empowered_sdg']
continuous_indicators: ['hhwi_cont']
indicator_labels:
  stunting: "Child stunting"
  wasting: "Child wasting"
  hhwi_cont: "Household wealth index"
  first_birth_u18: "First birth <18"
  w_empowerment_sdg: "Women's Empowerment"
completeness_threshold: 0.3
n_holdouts: 5
n_imputations: 5
fields:
  ids: ['cluster', 'bh_year', 'hh_id', 'w_id', 'birth_id', 'admin1_code', 'admin1_name']
  outcome: 'died'
  hidden: [
    'age_group', 'c_birth_year', 'c_alive', 'c_age_months', 'c_died_pnn', 'b_10y_prior',
    'w_sample_weight', 'int_month_cmc', 'c_died_age_months', 'c_birth_int', "w_born_cmc"
  ]
  spatial_covariates: [
    'Drought_Episodes', 'Elevation', 'Global_Human_Footprint', 'Land_Surface_Temperature',
    'Livestock_Cattle', 'Malaria_Incidence', 'Nightlights_Composite', 'Precipitation'
  ]
age_groups:
  a01mo: [1, 6]
  a06mo: [6, 12]
  a12mo: [12, 24]
  a24mo: [24, 36]
  a36mo: [36, 48]
  a48mo: [48, 60]
mbg_settings:
  modeling_crs: 'EPSG:4326'
  shapefile_settings:
    modeling_level: 2
    ids:
      adm0: ['ADM0_CODE','ADM0_NAME']
      adm1: ['ADM1_CODE','ADM1_NAME','ADM0_CODE','ADM0_NAME']
      adm2: ['ADM2_CODE','ADM2_NAME','ADM1_CODE','ADM1_NAME','ADM0_CODE','ADM0_NAME']
  covariate_settings:
    file_format: 'tif'
    add_intercept: TRUE
  pop_covariate_settings:
    covariate: 'worldpop_total'
    annual: TRUE
    transform: 'identity'
    normalize: FALSE
  stacking_settings:
    run_stacking: TRUE
    adm1_fixed_effects: TRUE
    submodels:
      enet: ~
      gam: ~
      gbm:
        verbose: FALSE
      treebag: ~
      nnet: ~
    cv:
      method: 'repeatedcv'
      number: 5
      repeats: 5
  inla_settings:
    sample_size_field: 'count'
    effects:
      covariates: TRUE
      spde: TRUE
      nugget: TRUE
      admin1: TRUE
    mesh:
      integrate_to_zero: TRUE
      cutoff: 0.05
    priors:
      range:
        threshold: 0.05
        prob_below: 0.05
      sigma:
        threshold: 1.0
        prob_above: 0.05
      fixed_effects:
        threshold: 1.0
        prob_above: 0.05
      nugget:
        threshold: 0.25
        prob_above: 0.01
      admin1:
        threshold: 0.5
        prob_above: 0.05
  prediction_settings:
    n_samples: 250
    ui_width: 0.95
    nugget_in_predict: TRUE
versions:
  model_results: '20240516'
  mbg_input_data: '20240805'
  mbg_stacking_cache: '20240805'
  mbg_model_results: '20240805'
directories:
  repo:
    versioned: FALSE
    path: '~/efs-mount/repos/usaid-mch-ml'
    files:
      model_specs: 'mbg_model_specs.csv'
      covariates_table: 'mbg_covariates_table.csv'
  r_package:
    versioned: FALSE
    path: '~/efs-mount/repos/usaid-mch-ml/r-package'
  model_results:
    versioned: TRUE
    path: '~/efs-mount/usaid/model_results'
  imputed_data:
    versioned: FALSE
    path: '~/efs-mount/usaid/imputed_data'
  mbg_input_data:
    versioned: TRUE
    path: '~/efs-mount/mbg_inputs/input_data'
  mbg_covariates:
    versioned: FALSE
    path: '~/efs-mount/mbg_inputs/covariates'
  mbg_stacking_cache:
    versioned: TRUE
    path: '~/efs-mount/mbg_inputs/stacking_cache'
  mbg_shapefile:
    versioned: FALSE
    path: '~/efs-mount/mbg_inputs/shp'
    files:
      adm0: 'adm0_subset.RDS'
      adm1: 'adm1_subset.RDS'
      adm2: 'adm2_subset.RDS'
  mbg_model_results:
    versioned: TRUE
    path: '~/efs-mount/mbg_outputs/'
    files:
      in_sample_results: 'in_sample_results.csv'
      out_of_sample_results: 'out_of_sample_results.csv'
      id_raster: 'id_raster.tif'
      cell_draws: 'cell_draws.RDS'
