countries: [
  "Cote D'Ivoire", "Ghana", "Indonesia", "Kenya", "Senegal", "Nigeria", "Philippines"
]
versions:
  prepared_data: '20240201'
directories:
  r_package:
    versioned: FALSE
    path: '~/repos/usaid-mch-ml/r-package'
  metadata:
    versioned: FALSE
    path: '~/temp_data/usaid-mch-ml/metadata'
    files:
      codebook: 'codebook_20240201.csv'
  prepared_data:
    versioned: TRUE
    path: '~/temp_data/usaid-mch-ml/prepared_data'
